### ISSUE TITLE
payment option not showing in the payment page

### ISSUE THREAD

**Issue by Kuntal32** [sveawebpay/magento2-checkout#1]
Hello,
     I have successfully installed sveawebpay/magento2-checkout module into my Magento 2 project but payment option not showing in the payment page. I have also enabled this module from admin panel. Please advice.

**Comment by TekniskSupport** [comment]
Hi Kuntal,

The payment method should be visible under store->configuration->sales->payment methods, when successfully configured you should get the checkout window when placing something in cart and going to checkout.

The payment method is not visible in the normal checkout process, it overrides Magento default checkout proccess and replaces it with a custom one as there are no need to enter addresses/customer details etc, they are provided from Svea whenever a customer places the order.

However if something is not right, it does not override the Magento default checkout process, this is probably what is happening to you.

You may want to check the logs in [magentofolder]/var/log/ to get a clue about what is not correctly configured.

I assume you have run the commands for upgrading db-schema, generated the dependency injection and flushed the cache. You may also need to rebuild frontend as well, as the module is provided with some javascript and css.

Best of luck,
 Iesus Webbhuset

**Comment by Kuntal32** [comment]
Hello,
    I have installed successfully. In Magento 2 admin panel I can see Svea Ekonomi Checkout section.
Also, I have enabled this module. But it's not showing in the frontend. Also, I can't check log because sveacheckout_debug.log is missing under log folder. I have attached screenshot of my admin panel.
![payment](https://user-images.githubusercontent.com/17197095/30483897-3e9e586a-9a46-11e7-87c9-daf28ab4ddc3.png)
thank you.

**Comment by TekniskSupport** [comment]
Hi,

You will need to enter valid credentials for the integration between your shop and Svea to work properly, if credentials are missing the call fails and the checkout will not render.

Kind Regards
Iesus Webbhuset

**Comment by Kuntal32** [comment]
Thank you.
